buy_me_a_coffee: NamelessNanashi
github: NanashiTheNameless
ko_fi: NanashiTheNameless
thanks_dev: u/gh/NanashiTheNameless
custom:
  - "https://www.paypal.me/NamelessNanashi"
  - "https://throne.com/NamelessNanashi"
